version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app_network

  entrytask:
    image: ${DOCKER_REGISTRY-}entrytask
    build:
      context: .
      dockerfile: EntryTask/Dockerfile
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - app_network

volumes:
  mariadb_data:

networks:
  app_network:
